# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 02:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')], verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')], verbose_name='Last name')),
                ('highest_education', models.CharField(choices=[('N', 'None'), ('H', 'High School Diploma'), ('T', 'Technical Diploma'), ('A', "Associate's Degree"), ('B', "Bachelor's Degree"), ('M', "Master's Degree"), ('D', 'Doctorate Degree')], max_length=1)),
                ('education_status', models.CharField(choices=[('G', 'Graduated'), ('I', 'In Progress'), ('N', 'Not Complete')], max_length=1)),
                ('program', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')])),
                ('years_experience', models.PositiveIntegerField()),
                ('relevant_job_employer', models.CharField(max_length=50)),
                ('relevant_job_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_target', models.CharField(choices=[('R', 'Recruiter'), ('C', 'Candidate'), ('S', 'System')], max_length=1)),
                ('feedback_contents', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Candidate')),
            ],
        ),
        migrations.CreateModel(
            name='PostSurvey',
            fields=[
                ('postsurvey_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_one_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('question_two_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('question_three_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('question_four_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('question_five_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='PreSurvey',
            fields=[
                ('presurvey_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_one_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('question_two_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('question_three_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('question_four_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('question_five_response', models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], max_length=1)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')])),
                ('employer', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')])),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetic characters allowed')])),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('transcript_id', models.AutoField(primary_key=True, serialize=False)),
                ('speaker', models.CharField(choices=[('C', 'Candidate'), ('R', 'Recruiter')], max_length=1)),
                ('line_number', models.PositiveIntegerField()),
                ('line_contents', models.CharField(max_length=2000)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(8, 'Your username must contain at least 8 characters.')], verbose_name='Username')),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8, 'Your username must contain at least 8 characters.')], verbose_name='Password')),
            ],
        ),
        migrations.AddField(
            model_name='recruiter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.User'),
        ),
        migrations.AddField(
            model_name='interview',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Recruiter'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='interview',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Interview'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.User'),
        ),
    ]
