# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-30 18:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8, 'Your username must contain at least 8 characters.')], verbose_name='Username'),
        ),
    ]
