# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20161030_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='education_status',
            field=models.CharField(choices=[('G', 'Graduated'), ('I', 'In Progress'), ('N', 'Not Complete')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='highest_education',
            field=models.CharField(choices=[('N', 'None'), ('H', 'High School Diploma'), ('T', 'Technical Diploma'), ('A', "Associate's Degree"), ('B', "Bachelor's Degree"), ('M', "Master's Degree"), ('D', 'Doctorate Degree')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_target',
            field=models.CharField(choices=[('R', 'Recruiter'), ('C', 'Candidate'), ('S', 'System')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='question_five_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='question_four_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='question_one_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='question_three_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='postsurvey',
            name='question_two_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='question_five_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='question_four_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='question_one_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='question_three_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='presurvey',
            name='question_two_response',
            field=models.CharField(choices=[(1, 'Strongly disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=3, max_length=1),
        ),
    ]
